# Generated by Django 4.2.7 on 2023-11-30 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProdExChange', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('price', models.FloatField()),
                ('discount_price', models.FloatField(blank=True, null=True)),
                ('slug', models.SlugField()),
                ('description', models.TextField()),
            ],
        ),
    ]
